services:
  postgres:
    image: postgres:latest
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: n8n_pass
      POSTGRES_DB: n8n_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres-exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=postgresql://n8n_user:n8n_pass@postgres:5432/n8n_db?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_pass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin_pass
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_METRICS=true
      - N8N_METRICS_ACTIVE=true
      - N8N_METRICS_ENDPOINT=/metrics
      - WEBHOOK_URL=http://localhost/webhook
    depends_on:
      - postgres
    networks:
      n8n_network:
        aliases:
          - n8n
    expose:
      - 5678
    volumes:
      - n8n_data:/home/node/.n8n

  nginx:
    image: nginx:latest
    container_name: n8n-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - n8n
    networks:
      - n8n_network

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    restart: unless-stopped
    command:
    - "-nginx.scrape-uri=http://n8n-nginx:8080/status"
    ports:
      - "9113:9113"
    networks:
      - n8n_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - n8n_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin # default password
    depends_on:
      - prometheus
    networks:
      - n8n_network

volumes:
  postgres_data:
  n8n_data:
  prometheus_data:

networks:
  n8n_network:
    driver: bridge