global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'n8n'
    metrics_path: /metrics
    static_configs:
      - targets:
        - n8n-postgresql-high-availability-system-n8n-1:5678
        - n8n-postgresql-high-availability-system-n8n-2:5678
        - n8n-postgresql-high-availability-system-n8n-3:5678

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']